### ISSUE TITLE
Cannot run gatsby develop

### ISSUE THREAD

**Issue by bilogic** [CartQL/gatsby-cartql-starter#12]
Running ```gatsby develop``` ends with the follow error

```
 ERROR #98123  WEBPACK

Generating SSR bundle failed

Can't resolve 'isomorphic-fetch' in '/var/www/gatsby-cartql-starter'

File: gatsby-ssr.js


 ERROR

Cannot read property 'activities' of undefined
```

**Comment by notrab** [comment]
This feels like more of an issue with your implementation. What is “activities”?

**Comment by bilogic** [comment]
My implementation? Do you mean my changes to this code base? There was none.

I cloned this repo, and did a ```npm install```, after it was done, I had to do ```npm audit fix```.
Next came ```gatsby develop``` and I see this error.

**Comment by notrab** [comment]
Ah ok. Thanks!

Have you tried installing `isomorphic-fetch`

Odd one. It must have got removed from package.json at some point.

**Comment by notrab** [comment]
I've gone ahead and added the fetch import dependency and added it to the Apollo Client instance. (as it's required by that)
